baseURL = "/"
languageCode = "ja-JP"
defaultContentLanguage = "ja"

title = "Jun Nishii"
theme = "hugo-theme-learn"
themesdir = "themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir = false


# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics.ID = "UA-48444845-1"

[params]
#  editURL = "https://github.com/matcornic/hugo-theme-learn/edit/master/exampleSite/content/"
  description = "Nishii's Notebook"
  author = "Jun Nishii"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = true
  themeVariant = "ocean"
  titleSeparator = "::"

[outputs]
home = [ "HTML", "RSS", "JSON"]

#####

#[[menu.shortcuts]]
#name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
#url = "/credits"
#weight = 30

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-home'></i> Nishii's homepage"
url = "http://bcl.sci.yamaguchi-u.ac.jp/~jun/"
weight = 30
